# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d6aab7711e3adfcfb050f9028611a8d76072ee01535aa114e826db8a617c257902aea1873bbfc28f2a6cb888f4e7d59edfcdc8479631bd42d8ee5ed1cf06065

test:
  secret_key_base: 92d5f4f72919698f9d6c00b72e019bd66e23883924d338aff11891ef24286be87a8bceb3bf970667afdcb8febafd3d353b03650232818a71bc85f788e8f18f71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
